<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Journal Entry {{ $transaction->reference }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            color: #333;
            font-size: 12px;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
        }

        .header h1 {
            margin: 0;
            font-size: 24px;
            color: #333;
        }

        .header p {
            margin: 5px 0;
            color: #666;
        }

        .transaction-info {
            margin-bottom: 20px;
        }

        .transaction-info table {
            width: 100%;
        }

        .transaction-info table td {
            padding: 5px;
            vertical-align: top;
        }

        .transaction-info table td:first-child {
            font-weight: bold;
            width: 150px;
        }

        .entries-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        .entries-table th {
            background-color: #f5f5f5;
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        .entries-table td {
            border: 1px solid #ddd;
            padding: 8px;
        }

        .entries-table .amount {
            text-align: right;
        }

        .entries-table .total-row {
            font-weight: bold;
            background-color: #f5f5f5;
        }

        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #888;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>Journal Entry</h1>
        <p>{{ $transaction->organization->name }}</p>
        <p>{{ now()->format('Y-m-d H:i') }}</p>
    </div>

    <div class="transaction-info">
        <table>
            <tr>
                <td>Reference:</td>
                <td>{{ $transaction->reference }}</td>
                <td>Status:</td>
                <td>{{ ucfirst($transaction->status) }}</td>
            </tr>
            <tr>
                <td>Date:</td>
                <td>{{ $transaction->date->format('Y-m-d') }}</td>
                <td>Created By:</td>
                <td>{{ $transaction->creator->name ?? 'Unknown' }}</td>
            </tr>
            <tr>
                <td>Description:</td>
                <td colspan="3">{{ $transaction->description }}</td>
            </tr>
            @if ($transaction->jobBooking)
                <tr>
                    <td>Job Number:</td>
                    <td colspan="3">{{ $transaction->jobBooking->job_number }} - {{ $transaction->jobBooking->title }}
                    </td>
                </tr>
            @endif
        </table>
    </div>

    <h3>Journal Entries</h3>
    <table class="entries-table">
        <thead>
            <tr>
                <th>Account</th>
                <th>Description</th>
                <th>Debit</th>
                <th>Credit</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($transaction->entries as $entry)
                <tr>
                    <td>{{ $entry->account->account_number }} - {{ $entry->account->name }}</td>
                    <td>{{ $entry->description }}</td>
                    <td class="amount">{{ $entry->debit > 0 ? $entry->formatMoney($entry->debit) : '' }}</td>
                    <td class="amount">{{ $entry->credit > 0 ? $entry->formatMoney($entry->credit) : '' }}</td>
                </tr>
            @endforeach
            <tr class="total-row">
                <td colspan="2" style="text-align:right">Totals</td>
                <td class="amount">{{ $transaction->formatMoney($transaction->entries->sum('debit')) }}</td>
                <td class="amount">{{ $transaction->formatMoney($transaction->entries->sum('credit')) }}</td>
            </tr>
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by OSC Corporation Accounting System</p>
        <p>Transaction ID: {{ $transaction->id }} | Created: {{ $transaction->created_at }}</p>
    </div>
</body>

</html>
