name: Laravel CI

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

permissions:
  contents: write

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm install

      - name: Run Pint
        run: php vendor/bin/pint

      # - name: Commit Changes
      #   uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: fix code style
      #     commit_options: "--no-verify"
      #     file_pattern: |
      #       **/*
      #       !.github/workflows/*

  build:
    name: Build App
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          tools: composer:v2
          coverage: xdebug

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev --no-progress

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install Node Dependencies
        run: npm install

      - name: Build Assets
        run: npm run build

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Cache Configuration
        run: php artisan config:cache

      - name: Cache Routes
        run: php artisan route:cache

      - name: Optimize
        run: php artisan optimize

      # - name: Run Tests
      #   run: ./vendor/bin/phpunit
